sudo: required
services:
  - docker
addons:
  apt:
    sources:
      - heroku
    packages:
      - heroku-toolbelt
language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
install:
  - npm i
  - npm i -g codecov
script:
  - npm test
  - codecov
after_success:
  - "./docker-deploy.sh"
