sudo: required
services:
  - docker
addons:
  apt:
    sources:
      - heroku
    packages:
      - heroku-toolbelt
language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
install:
  - npm i
  - npm i -g codecov
script:
  - npm test
  - codecov
after_success:
  - "./docker-deploy.sh"
