sudo: required
dist: xenial
services:
  - docker
  - postgresql
language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
before_script:
  - psql -c "CREATE DATABASE rv_test;" -U postgres
  - psql -c "CREATE USER rv WITH PASSWORD 'unsecure';" -U postgres  
install:
  - npm i
  - npm i -g codecov
script:
  - npm test
  - codecov
after_success:
  - "./docker-deploy.sh"
