version: '3'
volumes:
  rv-postgres-data:
services:
  rv-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DB_HOST=db
      - DB_USERNAME=rvadmin
      - DB_PASSWORD=unsecure
      - DB_NAME=rv
      - DB_PORT=5432
      - JWT_SECRET=unsecure
      - JWT_ADMIN_SECRET=unsecure
    volumes:
      - ./src:/usr/src/app/src
      - ./logs:/usr/src/app/logs
  db:
    image: postgres:10-alpine
    ports:
      - 5432:5432
    volumes:
      - rv-postgres-data:/var/lib/postgresql/data
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=rvadmin
      - POSTGRES_PASSWORD=unsecure
      - POSTGRES_DB=rv_dev
