// These should not be changed as database already contains data with the ids
const actions = {
	ITEM_CREATED: 1,
	CHANGED_DESCRIPTION: 2,
	CHANGED_WEIGHT: 3,
	CHANGED_PRODUCT_GROUP: 4,
	BOUGHT_BY: 5,
	CHANGED_BUYPRICE: 6,
	CHANGED_SELLPRICE: 7,
	CHANGED_COUNT_OR_INVENTORIED_BUT_NOT_BOUGHT: 8,
	USER_CREATED: 9,
	LOGGED_IN: 10,
	LOGGED_OUT: 11,
	LOGIN_FAILED: 12,
	FAILED_PASSWORD_CHANGE: 13,
	ADMIN_CHANGED_PASSWORD: 14,
	SELF_CHANGED_PASSWORD: 15,
	WITHDREW_MONEY: 16,
	DEPOSITED_MONEY: 17, // Deprecated pls use CASH or BANKTRANSFER instead
	CHANGED_ROLE: 18,
	CHANGED_NAME: 19,
	CHANGED_UNIVIDENT: 20,
	CHANGED_BUZZERLIMIT: 21,
	CHANGED_FGCOLOR: 22,
	CHANGED_BGCOLOR: 23,
	BOX_CREATED: 24,
	CHANGED_BOX_ITEM_COUNT: 25,
	DEPOSITED_MONEY_CASH: 26,
	DEPOSITED_MONEY_BANKTRANSFER: 27,
	PRODUCT_RETURNED: 28,
	PRODUCT_BUY_IN: 29,
};

export default actions;
