name: Build

on:
    push:
        branches: [develop, master]
    pull_request:
        branches: [develop, master]
    release:
        types: [published]

jobs:
    test:
        runs-on: ubuntu-latest
        container: node:20-slim

        services:
            postgres:
                image: postgres
                env:
                    POSTGRES_USER: rv
                    POSTGRES_PASSWORD: unsecure
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
            - name: Cache NPM dependencies
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'
            - name: Install NPM dependencies
              run: npm ci
            - name: Execute test suites
              run: npm test
              env:
                  NODE_ENV: test
                  PORT: 4040
                  DB_HOST: postgres
                  DB_USERNAME: rv
                  DB_PASSWORD: unsecure
                  DB_NAME: rv
                  DB_PORT: 5432
                  JWT_SECRET: unsecure1
                  JWT_ADMIN_SECRET: unsecure2
            - name: Generate the code coverage report
              uses: codecov/codecov-action@v3
    lint:
        runs-on: ubuntu-latest
        container: node:20-slim

        steps:
            - name: Checkout the repository
              uses: actions/checkout@v4
            - name: Cache NPM dependencies
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'npm'
            - name: Install NPM dependencies
              run: npm ci
            - name: Lint and check formatting with biome
              run: npm run lint
